alter system flush shared_pool;
alter session set statistics_level = all;
alter session set optimizer_adaptive_statistics = false;
set serveroutput off
drop table bricks
  cascade constraints purge;
drop table colours
  cascade constraints purge;
cl scr
create table colours (
  colour varchar2(10)
    not null 
    primary key,
  rgb_hex_code varchar2(6)
    not null
    unique
);

create table bricks (
  brick_id integer --generated by default on null as identity 
    not null
    primary key,
  colour varchar2(10)
    not null,
  shape  varchar2(10)
    not null,
  weight integer
    not null,
  notes  varchar2(50)
    not null
);

insert into colours values ( 'red', 'FF0000' );
insert into colours values ( 'blue', '00FF00' );
insert into colours values ( 'green', '0000FF' );

insert into bricks
with rws as (
  select level brick_id,
         floor ( 1000 / level ) + 1 v
  from   dual
  connect by level <= 9000
)
  select brick_id, 
         'red', 
         'cylinder',
         v,
         rpad ( 'notes', 50, 's' )
  from   rws;
  
insert into bricks
with rws as (
  select level + 10000 brick_id,
         floor ( 1000 / level ) v
  from   dual
  connect by level <= 1000
)
  select brick_id, 
         'blue', 
         'prism',
         v,
         rpad ( 'notes', 50, 's' )
  from   rws;
  
insert into bricks
with rws as (
  select level + 20000 brick_id,
         floor ( 1000 / level ) v
  from   dual
  connect by level <= 500
)
  select brick_id, 
         'green', 
         'star',
         v,
         rpad ( 'notes', 50, 's' )
  from   rws;

commit;

exec dbms_stats.gather_table_stats ( user, 'colours' ) ;
cl scr