@sql-atoh-202511-setup.sql
/*  Weather sensor data collection 
 - Sensors at various locations
 - Record some or all of temp/wind/rainfall at each
 - Handle unit conversions

 - Decisions
 Datetimes - date vs timestamp?
 Optional values - nullable vs tables?
 FKs on delete - cascade vs no action?
 Calc values - virtual vs materialized?
*/


create table sensors ( 
  sensor_id integer generated by default as identity
    constraint sensor_pk primary key, 
  latitude  number(8, 6) not null
    constraint sens_lat_c check (
      latitude between -90 and 90
    ),
  longitude number(9, 6) not null
    constraint sens_long_c check (
      longitude between -180 and 180
    )
);



/* One table for all measurement types */
create table sensor_readings ( 
  sensor_id           references sensors
    /* on delete cascade /**/,
  reading_datetime    
    -- date not null,
    -- timestamp not null,
/*  temperature_in_c    number, 
  pressure_in_mbar    number,
  relative_humidity   number check ( relative_humidity between 0 and 100 ),
  wind_speed_m_per_s  number check ( wind_speed_m_per_s >= 0 ), 
  wind_direction      number check ( wind_direction between 0 and 360 ),
  rainfall_mm_per_min number check ( rainfall_mm_per_min >= 0 ), 
  constraint sere_heat_readings_c  -- all heat values or none
    check ( 
      nvl2 ( temperature_in_c, 1, 0 ) + 
      nvl2 ( pressure_in_mbar, 1, 0 ) + 
      nvl2 ( relative_humidity, 1, 0 ) in ( 0, 3 ) 
    ),
  constraint sere_wind_readings_c  -- all wind values or none
    check ( 
      nvl2 ( wind_direction, 1, 0 ) + 
      nvl2 ( wind_speed_m_per_s, 1, 0 ) in ( 0, 2 ) 
    ),/**/
  constraint sensor_reading 
    primary key ( sensor_id, reading_datetime )
);



/* Separate tables for each  */
create table sensor_heat_readings ( 
  sensor_id, reading_datetime,
  foreign key ( sensor_id, reading_datetime )
    references sensor_readings
    -- on delete cascade 
    deferrable initially immediate,
  temperature_in_c    number not null, 
  pressure_in_mbar    number not null,
  relative_humidity   number not null check ( relative_humidity between 0 and 100 ),
  constraint sensor_heat_reading 
    primary key ( sensor_id, reading_datetime )
);

create table sensor_wind_readings ( 
  sensor_id, reading_datetime,
  foreign key ( sensor_id, reading_datetime )
    references sensor_readings
    -- on delete cascade 
    deferrable initially immediate,
  wind_speed_m_per_s  number not null check ( wind_speed_m_per_s >= 0 ),  
  wind_direction      number not null check ( wind_direction between 0 and 360 ),
  constraint sensor_wind_reading 
    primary key ( sensor_id, reading_datetime )
);

create table sensor_rain_readings ( 
  sensor_id, reading_datetime,
  foreign key ( sensor_id, reading_datetime )
    references sensor_readings
    -- on delete cascade 
    deferrable initially immediate,
  rainfall_mm_per_min number not null check ( rainfall_mm_per_min >= 0 ), 
  constraint sensor_rain_reading 
    primary key ( sensor_id, reading_datetime )
);

/* Load some sensors in */
insert into sensors ( latitude, longitude )
values ( 51.5074,-0.1278 ), 
       ( 53.4808,-2.2426 ), 
       ( 55.9533,-3.1883 ), 
       ( 52.4862,-1.8904 ), 
       ( 53.8008,-1.5491 ); 

commit;



/* Single table insert */
insert into sensor_readings (
  sensor_id, reading_datetime, temperature_in_c, pressure_in_mbar, 
  relative_humidity, wind_speed_m_per_s, wind_direction, rainfall_mm_per_min
) values 
  ( 1, sysdate,           15,   1013, 60,   5,   180,   0 ),
  ( 1, sysdate + 10/1440, 15.2, 1014, 62,   5.5, 190,   0 ),
  ( 1, sysdate + 20/1440, 15.4, 1015, 64,   6,   200,   0.1 ),
  ( 1, sysdate + 30/1440, 15.3, 1013, 65,   5.8, 185,   0 ),
  ( 2, sysdate          , null, null, null, 4.5, 170,   null ),
  ( 2, sysdate + 10/1440, null, null, null, 4,   160,   null ),
  ( 2, sysdate + 20/1440, null, null, null, 3.5, 150,   null ),
  ( 2, sysdate + 30/1440, null, null, null, 3,   140,   null ),
  ( 3, sysdate,           null, null, null, null, null, 0 ),
  ( 3, sysdate + 10/1440, null, null, null, null, null, 0 ),
  ( 3, sysdate + 20/1440, null, null, null, null, null, 0.1 ),
  ( 3, sysdate + 30/1440, null, null, null, null, null, 0 ),
  ( 4, sysdate,           15,   1013, 60,   null, null, null ),
  ( 4, sysdate + 10/1440, 15.2, 1014, 62,   null, null, null ),
  ( 4, sysdate + 20/1440, 15.4, 1015, 64,   null, null, null ),
  ( 4, sysdate + 30/1440, 15.3, 1013, 65,   null, null, null ),
  ( 5, sysdate,           15,   1013, 60,   5,    180,  0 ),
  ( 5, sysdate + 10/1440, 15.2, 1014, 62,   5.5,  190,  0 ),
  ( 5, sysdate + 20/1440, 15.4, 1015, 64,   6,    200,  0.1 ),
  ( 5, sysdate + 30/1440, 15.3, 1013, 65,   5.8,  185,  0 );

rollback;






/* 239.9 Multi-row INSERT .. SET statement */
insert into sensor_readings
set 
  ( sensor_id = 1, reading_datetime = sysdate,           temperature_in_c = 15,   pressure_in_mbar = 1013, relative_humidity = 60, wind_speed_m_per_s = 5, wind_direction = 180, rainfall_mm_per_min = 0 ),
  ( sensor_id = 1, reading_datetime = sysdate + 10/1440, temperature_in_c = 15.2, pressure_in_mbar = 1014, relative_humidity = 62, wind_speed_m_per_s = 5.5, wind_direction = 190, rainfall_mm_per_min = 0 ),
  ( sensor_id = 1, reading_datetime = sysdate + 20/1440, temperature_in_c = 15.4, pressure_in_mbar = 1015, relative_humidity = 64, wind_speed_m_per_s = 6, wind_direction = 200, rainfall_mm_per_min = 0.1 ),
  ( sensor_id = 1, reading_datetime = sysdate + 30/1440, temperature_in_c = 15.3, pressure_in_mbar = 1013, relative_humidity = 65, wind_speed_m_per_s = 5.8, wind_direction = 185, rainfall_mm_per_min = 0 ),
  ( sensor_id = 2, reading_datetime = sysdate,           wind_speed_m_per_s = 4.5, wind_direction = 170 ),
  ( sensor_id = 2, reading_datetime = sysdate + 10/1440, wind_speed_m_per_s = 4,   wind_direction = 160 ),
  ( sensor_id = 2, reading_datetime = sysdate + 20/1440, wind_speed_m_per_s = 3.5, wind_direction = 150 ),
  ( sensor_id = 2, reading_datetime = sysdate + 30/1440, wind_speed_m_per_s = 3,   wind_direction = 140 ),
  ( sensor_id = 3, reading_datetime = sysdate,           rainfall_mm_per_min = 0 ),
  ( sensor_id = 3, reading_datetime = sysdate + 10/1440, rainfall_mm_per_min = 0 ),
  ( sensor_id = 3, reading_datetime = sysdate + 20/1440, rainfall_mm_per_min = 0.1 ),
  ( sensor_id = 3, reading_datetime = sysdate + 30/1440, rainfall_mm_per_min = 0 ),
  ( sensor_id = 4, reading_datetime = sysdate,           temperature_in_c = 15,   pressure_in_mbar = 1013, relative_humidity = 60 ),
  ( sensor_id = 4, reading_datetime = sysdate + 10/1440, temperature_in_c = 15.2, pressure_in_mbar = 1014, relative_humidity = 62 ),
  ( sensor_id = 4, reading_datetime = sysdate + 20/1440, temperature_in_c = 15.4, pressure_in_mbar = 1015, relative_humidity = 64 ),
  ( sensor_id = 4, reading_datetime = sysdate + 30/1440, temperature_in_c = 15.3, pressure_in_mbar = 1013, relative_humidity = 65 ),
  ( sensor_id = 5, reading_datetime = sysdate,           temperature_in_c = 15,   pressure_in_mbar = 1013, relative_humidity = 60, wind_speed_m_per_s = 5, wind_direction = 180, rainfall_mm_per_min = 0 ),
  ( sensor_id = 5, reading_datetime = sysdate + 10/1440, temperature_in_c = 15.2, pressure_in_mbar = 1014, relative_humidity = 62, wind_speed_m_per_s = 5.5, wind_direction = 190, rainfall_mm_per_min = 0 ),
  ( sensor_id = 5, reading_datetime = sysdate + 20/1440, temperature_in_c = 15.4, pressure_in_mbar = 1015, relative_humidity = 64, wind_speed_m_per_s = 6, wind_direction = 200, rainfall_mm_per_min = 0.1 ),
  ( sensor_id = 5, reading_datetime = sysdate + 30/1440, temperature_in_c = 15.3, pressure_in_mbar = 1013, relative_humidity = 65, wind_speed_m_per_s = 5.8, wind_direction = 185, rainfall_mm_per_min = 0 );

rollback;





/* 23.9 INSERT .. SELECT .. BY NAME */
insert into sensor_readings
by name
select sensor_id,
       g.*
from   sensors 
cross  join lateral (
  select * from generate_sensor_readings ( 100, sensor_id ) 
) g;

commit;






/* Separate tables for each reading type
   Multitable insert when using separate tables */
insert all 
  when true then 
    into sensor_readings 
    set  sensor_id = sensor_id, reading_datetime = reading_datetime 
  when temperature_in_c is not null then 
    into sensor_heat_readings 
    set  sensor_id = sensor_id, reading_datetime = reading_datetime,
         temperature_in_c = temperature_in_c, pressure_in_mbar = pressure_in_mbar, relative_humidity = relative_humidity 
  when wind_speed_m_per_s is not null then 
    into sensor_wind_readings 
    set  sensor_id = sensor_id, reading_datetime = reading_datetime,
         wind_speed_m_per_s = wind_speed_m_per_s, wind_direction = wind_direction 
  when rainfall_mm_per_min is not null then 
    into sensor_rain_readings 
    set  sensor_id = sensor_id, reading_datetime = reading_datetime,
         rainfall_mm_per_min = rainfall_mm_per_min 
select sensor_id,
       g.*
from   sensors 
cross  join lateral (
  select * from generate_sensor_readings ( 100, sensor_id ) 
) g;




/* Insert order for multitable inserts is non-deterministic 
   May need to defer FK constraints */
set constraints all deferred;
commit;






/* Check the data */
select sens.sensor_id, 
       sere.reading_datetime,
       temperature_in_c,
       pressure_in_mbar,
       relative_humidity,
       wind_speed_m_per_s,
       wind_direction,
       rainfall_mm_per_min
from   sensors sens
left   join sensor_readings sere on sens.sensor_id = sere.sensor_id
--  Comment in if separate tables 
/*left   join sensor_rain_readings serr on sere.sensor_id = serr.sensor_id and sere.reading_datetime = serr.reading_datetime
left   join sensor_wind_readings sewr on sere.sensor_id = sewr.sensor_id and sere.reading_datetime = sewr.reading_datetime
left   join sensor_heat_readings sehr on sere.sensor_id = sehr.sensor_id and sere.reading_datetime = sehr.reading_datetime /**/
/




/* Delete sensor 1 */
declare 
  remove_sensor_id integer := 1;
begin
/*
  delete sensor_heat_readings
  where  sensor_id = remove_sensor_id;
  delete sensor_wind_readings
  where  sensor_id = remove_sensor_id;
  delete sensor_rain_readings
  where  sensor_id = remove_sensor_id;
/**/
/*
  delete sensor_readings
  where  sensor_id = remove_sensor_id;
/**/
  delete sensors
  where  sensor_id = remove_sensor_id;
end;
/

rollback;






/* Create a view instead? */
create or replace view sensor_data as
  select sens.sensor_id, 
         sere.reading_datetime,
         temperature_in_c,
         pressure_in_mbar,
         relative_humidity,
         wind_speed_m_per_s,
         wind_direction,
         rainfall_mm_per_min
  from   sensors sens
  left   join sensor_readings sere on sens.sensor_id = sere.sensor_id
  -- Comment in if separate tables 
  /*left   join sensor_rain_readings serr on sere.sensor_id = serr.sensor_id and sere.reading_datetime = serr.reading_datetime
  left   join sensor_wind_readings sewr on sere.sensor_id = sewr.sensor_id and sere.reading_datetime = sewr.reading_datetime
  left   join sensor_heat_readings sehr on sere.sensor_id = sehr.sensor_id and sere.reading_datetime = sehr.reading_datetime/**/
/

select * from sensor_data;






/* Can't write to the view without instead of DML triggers :(  */
delete sensor_data
where  sensor_id = 1;

insert into sensor_data (
  sensor_id, reading_datetime, temperature_in_c, pressure_in_mbar, 
  relative_humidity, wind_speed_m_per_s, wind_direction, rainfall_mm_per_min
) values 
  ( 1, sysdate, 15,   1013, 60,   5,   180,   0 );







/* Use JSON-relational duality views! */
create or replace json relational duality view sensor_data as
  select
    json {
      '_id' : json {  
          'sensor_id' : sensor_id, 'reading_datetime' : reading_datetime
      },'sensor' : (
        select json {
          'sensor_id' : sensor_id, 'latitude' : latitude, 'longitude' : longitude
        }
        from  sensors sens with insert 
        where sens.sensor_id = sere.sensor_id
      ), 'sensor_heat_readings' : 
        -- ( select
            json { 
            -- 'heat_sensor_id' : sensor_id, 'heat_reading_datetime' : reading_datetime,
              'temperature_in_c' : temperature_in_c,
              'pressure_in_mbar' : pressure_in_mbar,
              'relative_humidity' : relative_humidity
            }
          /* from sensor_heat_readings sehr with insert delete
          where sehr.sensor_id = sere.sensor_id and sehr.reading_datetime = sere.reading_datetime
       )/**/, 'sensor_wind_readings' : 
        -- ( select
            json { 
            -- 'wind_sensor_id' : sensor_id, 'wind_reading_datetime' : reading_datetime,
              'wind_speed_m_per_s' : wind_speed_m_per_s,
              'wind_direction' : wind_direction
            }
          /* from sensor_wind_readings sewr with insert delete
          where sewr.sensor_id = sere.sensor_id and sewr.reading_datetime = sere.reading_datetime
      ) /**/, 'sensor_rain_readings' : 
        -- ( select
            json { 
             -- 'rain_sensor_id' : sensor_id, 'rain_reading_datetime' : reading_datetime,
              'rainfall_mm_per_min' : rainfall_mm_per_min
            }
          /*from sensor_rain_readings sehr with insert delete
          where sehr.sensor_id = sere.sensor_id and sehr.reading_datetime = sere.reading_datetime
      )/**/
    }
  from sensor_readings sere with insert delete
/

select * from sensor_data;






/* Can add and remove from DV without extra coding */
-- set deferrable constraints if separate tables
set constraints all deferred;

/* Adding readings for a new sensor */
select * from sensors
where  sensor_id = 0;

insert into sensor_data
values ( 
  json ( 
    '{
      "_id":{"sensor_id":0,"reading_datetime":"2025-10-12T00:17:22"},
      "sensor":{"sensor_id":0,"latitude":51.5074,"longitude":-0.1278},
      "sensor_heat_readings": { ' || 
        --  ' "heat_sensor_id" : 0, "heat_reading_datetime":"2025-10-12T00:17:22", ' ||
         ' "temperature_in_c":5.374,"pressure_in_mbar":1080, "relative_humidity" : 80},
      "sensor_wind_readings": { ' || 
        -- ' "wind_sensor_id" : 0, "wind_reading_datetime":"2025-10-12T00:17:22", ' || 
        ' "wind_speed_m_per_s":1.6319955756382634, "wind_direction":120},
      "sensor_rain_readings": { ' || 
        -- ' "rain_sensor_id" : 0, "rain_reading_datetime":"2025-10-12T00:17:22", ' || 
        ' "rainfall_mm_per_min":0.6}
    } ' 
  ) 
);

select * from sensor_data seda
where  seda.data."_id".sensor_id = 0;

delete sensor_data seda
where  seda.data."_id".sensor_id = 0;

/* Readings is root table, so parent sensor rows remain */
select * from sensors
where  sensor_id = 0;

rollback;





/* DV with sensors as root */
create or replace json relational duality view sensor_data as
  select
    json {
      '_id' : sensor_id, 'latitude' : latitude, 'longitude' : longitude,
      'sensor_readings' : [
        select json {
          'sensor_id' : sensor_id,
          'reading_datetime' : reading_datetime
        -- } from   sensor_readings sere with insert delete
        -- where  sens.sensor_id = sere.sensor_id ]
      , 'sensor_heat_readings' : 
        -- [ select
            json { 
              -- 'heat_sensor_id' : sensor_id, 'heat_reading_datetime' : reading_datetime,
              'temperature_in_c' : temperature_in_c,
              'pressure_in_mbar' : pressure_in_mbar,
              'relative_humidity' : relative_humidity
            }
          -- from sensor_heat_readings sehr with insert delete
          -- where sehr.sensor_id = sens.sensor_id ]
      , 'sensor_wind_readings' : 
        -- [ select
            json { 
              -- 'wind_sensor_id' : sensor_id, 'wind_reading_datetime' : reading_datetime,
              'wind_speed_m_per_s' : wind_speed_m_per_s,
              'wind_direction' : wind_direction
            }
            -- from sensor_wind_readings sewr with insert delete
          -- where sewr.sensor_id = sens.sensor_id
      -- ]
      , 'sensor_rain_readings' : 
        -- [ select
            json { 
              -- 'rain_sensor_id' : sensor_id, 'rain_reading_datetime' : reading_datetime,
              'rainfall_mm_per_min' : rainfall_mm_per_min
            }
          -- from sensor_rain_readings sehr with insert delete
          -- where sehr.sensor_id = sens.sensor_id
        -- } from   sensor_readings sere with insert delete
        -- where  sens.sensor_id = sere.sensor_id
      ]
    }
  from sensors sens with insert delete
/

/* We now have row/sensor, instead of row/reading */
select * from sensor_data;






-- Load data in; set deferrable constraints
set constraints all deferred;

insert into sensor_data
values ( json ( 
  '{"_id":0,"latitude":51.5074,"longitude":-0.1278,
    "sensor_readings":[
      {"sensor_id":0,"reading_datetime":"2025-10-12T00:00" ' || 
    -- ' } ' || 
    -- ' ] ' ||
    ', "sensor_heat_readings": ' || 
    -- ' [ ' ||
    ' { ' ||
      -- ' "heat_sensor_id":0,"heat_reading_datetime":"2025-10-12T00:00", ' || 
      ' "temperature_in_c":5.374,"pressure_in_mbar":1080, "relative_humidity":80 } ' ||
    -- ' ] ' ||
    ', "sensor_wind_readings": ' || 
    -- ' [ ' ||
    ' { ' ||
      -- ' "wind_sensor_id":0,"wind_reading_datetime":"2025-10-12T00:00", ' || 
      ' "wind_speed_m_per_s":1.6319955756382634,"wind_direction":180 } ' || 
    -- ' ] ' || 
    ', "sensor_rain_readings": ' || 
    -- ' [ ' ||
    ' { ' ||
      -- ' "rain_sensor_id":0,"rain_reading_datetime":"2025-10-12T00:00", ' || 
      ' "rainfall_mm_per_min":0.6} ' || 
    -- ' } ' ||  -- if one table
    ' ] ' || 
   ' }'
  )
);

select * from sensor_data seda
where  seda.data."_id" = 0;

delete sensor_data seda
where  seda.data."_id" = 0;

/* Sensors is root table, so everything deleted */
select * from sensors
where  sensor_id = 0;

commit;








/* Dates vs timestamps
   Different duration calculations 
   date - date => number of days 
   timestamp - timestamp => interval (day to second) */
select sysdate - date'2025-01-01', 
       systimestamp - timestamp'2025-01-01 00:00:00';
/* Also note: fractional seconds for timestamp */




/* This impacts duration to seconds formula */
select 
  reading_datetime, 
  -- Date diff
  /*( reading_datetime - 
      lag ( reading_datetime ) over (
        date_order
      )
  ) * 86400 /**/ 
  -- Timestamp diff
  /*extract ( 
    minute from ( 
      reading_datetime - 
      lag ( reading_datetime ) over (
        date_order
      )
    ) 
  ) * 60 + extract ( 
    second from ( 
      reading_datetime - 
      lag ( reading_datetime ) over (
        date_order
      )
    ) 
  ) /**/
    as seconds_gap
from   sensor_readings
window date_order as (
  partition by sensor_id
  order by reading_datetime
);





/* Rolling 1-hour rainfall totals */
select sensor_id, reading_datetime, 
       sum ( rainfall_mm_per_min ) over ( 
         date_order range 
        --  interval '1' hour preceding  -- date and timestamp
        --  1/24 preceding  -- date only
       ) * 60 as past_hour_total
-- from   sensor_readings where rainfall_mm_per_min is not null
-- from   sensor_rain_readings
window date_order as (
  partition by sensor_id
  order by reading_datetime
);



/* Dates vs timestamp 
   Only timestamp supporrts time zones
*/
select timestamp'2025-01-01 00:00:00' at time zone 'Europe/London';
select date'2025-01-01' at time zone 'Europe/London';






/* Temp conversions */
create or replace function celcius_to_fahrenheit (
  degrees_celcius number
) return number deterministic as
begin
  dbms_session.sleep ( 0.02 ); -- simulate slow function
  return ( degrees_celcius / 5 * 9 ) + 32;
end;
/




set timing on
/* Unit conversion - calc on read or write? */
alter table 
  -- sensor_readings 
  -- sensor_heat_readings 
  add ( 
    temperature_in_f number as ( 
      celcius_to_fahrenheit ( temperature_in_c )
    ) 
    -- materialized  -- default is virtual
  ); 

/* Querying:
   Slow if virtual 
   Fast if materialized */
select sensor_id, 
       avg ( temperature_in_c ), 
       avg ( temperature_in_f )
-- from   sensor_readings where temperature_in_c is not null -- exclude sensors without heat readings
-- from   sensor_heat_readings
group  by sensor_id;




