cl scr
drop table accounts_tmp
  cascade constraints purge;
drop table accounts_upd
  cascade constraints purge;
drop table account_logins
  cascade constraints purge;
drop table accounts
  cascade constraints purge;
  
create table accounts (
  user_id integer 
    generated by default on null as identity 
    not null
    primary key,
  email_address varchar2(320)
    not null
    unique,
  full_name varchar2(256)
    not null,
  last_login_time timestamp(3)
    not null
);

create table account_logins (
  user_id 
    references accounts,
  login_datetime timestamp(3),
  constraint account_login_pk
  primary key ( 
    user_id, login_datetime 
  )
);



insert into accounts ( email_address, full_name, last_login_time )
with rws as (
  select level x from dual
  connect by level <= 100000
)
  select dbms_random.string ( 'l', 10 ) || '@' || dbms_random.string ( 'l', 6 ) || '.com',
         dbms_random.string ( 'l', 5 ) || ' ' || dbms_random.string ( 'l', 5 ),
         date'2000-01-01'
  from   rws;

truncate table account_logins;
exec dbms_random.seed ( 0 );
insert /*+ append */into account_logins
with rws as (
  select user_id, 
         ceil ( ( abs ( ( dbms_random.normal + 2 ) ) * 100 ) + 5 ) r
  from   accounts
)
select user_id, 
       timestamp'2021-06-01 00:00:00' - 
         numtodsinterval ( rn, 'day' ) + 
         numtodsinterval ( sin ( rn + user_id ), 'hour' )
from   rws, lateral (
  select level rn from dual
  connect by level <= r
)
order by 2;

commit;

exec dbms_stats.gather_table_stats ( user, 'accounts' );
exec dbms_stats.gather_table_stats ( user, 'account_logins' );