cl scr
set timing off
set pages 1000
set arrays 100
drop table quiz_results cascade constraints purge;
drop table users cascade constraints purge;
drop table quizzes cascade constraints purge;
drop table competitions cascade constraints purge;
drop table competition_types cascade constraints purge; 
drop table questions cascade constraints purge;
drop materialized view mv_results ;
drop materialized view year_stats;
drop materialized view year_stats_rollup;

create table users ( 
  user_id int primary key, username varchar2(100) unique
);

create table competition_types (
  competition_type_id int primary key, 
  type_name varchar2(10)
);

create table competitions ( 
  competition_id integer primary key,
  competition_name varchar2(30) not null,
  competition_type_id references competition_types
);

create table questions ( 
  question_id int generated by default on null as identity cache 1000 
    primary key,
  created_date date, 
  author_id references users,
  topic     varchar2(30),
  question  varchar2(200) default rpad ( 'question', 100, 'n' )
);

create table quizzes ( 
  quiz_id integer generated by default on null as identity cache 1000
    primary key , 
  start_date date,
  end_date   date,
  competition_id references competitions, 
  status     varchar2(10),
  notes      varchar2(500) default rpad ( 'notes', 500, 's' )
);

create table quiz_results ( 
  quiz_id integer, 
  user_id integer, 
  result_date date, 
  finish_date date, 
  pct_correct number(5,2), 
  seconds_taken integer,
  primary key ( quiz_id, user_id )
);

insert into competition_types values ( 1, 'WEEKLY' );
insert into competition_types values ( 2, 'CHAMPS' );
insert into competition_types values ( 3, 'DAILY' );
insert into competition_types values ( 4, 'ONEOFF' );

insert into competitions values ( 1, 'Oracle Database', 1 );
insert into competitions values ( 2, 'Logic', 1 );
insert into competitions values ( 3, 'SQL', 1 );
insert into competitions values ( 4, 'PL/SQL', 1 );
insert into competitions values ( 5, 'Database design', 1 );

insert into competitions values ( 6, 'Oracle Database', 2 );
insert into competitions values ( 7, 'Logic', 2 );
insert into competitions values ( 8, 'SQL', 2 );
insert into competitions values ( 9, 'PL/SQL', 2 );
insert into competitions values ( 10, 'Database design', 2 );

insert into competitions values ( 11, 'Oracle Database', 3 );
insert into competitions values ( 12, 'Logic', 3 );
insert into competitions values ( 13, 'SQL', 3 );
insert into competitions values ( 14, 'PL/SQL', 3 );
insert into competitions values ( 15, 'Database design', 3 );

insert into competitions values ( 16, 'Oracle Database', 4 );
insert into competitions values ( 17, 'Logic', 4 );
insert into competitions values ( 18, 'SQL', 4 );
insert into competitions values ( 19, 'PL/SQL', 4 );
insert into competitions values ( 20, 'Database design', 4 );

commit; 

set timing on
insert into users
with rws as ( select level x from dual connect by level <= 100000 ) 
select x, dbms_random.string ( 'l', 10 ) u
from rws;

commit;

insert into questions ( created_date, author_id, topic ) 
with rws as ( 
  select date'2010-01-01' + level + numtodsinterval ( dbms_random.value ( 1, 2880 ), 'minute' ) dt
  from dual 
  connect by level <= ( sysdate - date'2010-01-01' )
) 
select dt, greatest ( round ( abs ( ( dbms_random.normal * 10 ) + 25 ) ) , 1 ),
   case mod ( extract ( day from dt ) + rownum, 10 )
     when 0 then 'Tables'
     when 1 then 'Indexes'
     when 2 then 'Views' 
     when 3 then 'Joins'
     when 4 then 'Packages'
     when 5 then 'Procedures'
     when 6 then 'Bulk processing'
     when 7 then 'INSERT' 
     when 8 then 'Normalization'
     when 9 then 'Window functions'
   end
from rws;

-- weekly quizzes
insert into quizzes ( start_date, end_date, competition_id, status )
with dates_w as ( 
   select trunc ( date'2010-01-31', 'iyyy' ) + (( level - 1 ) * 7 ) dt 
   from dual 
   connect by level <= (
     trunc ( date'2024-03-01', 'iw' ) - trunc ( date'2010-01-31', 'iyyy' )
   ) / 7 
), dates_d as ( 
   select trunc ( date'2010-01-31', 'iyyy' ) + level dt
   from dual 
   connect by level <= (
     trunc ( date'2024-03-01', 'iw' ) - trunc ( date'2010-01-31', 'iyyy' )
   )  
), dates_y as ( 
   select trunc ( date'2010-01-31', 'iyyy' ) + numtoyminterval ( level - 1 , 'year' ) dt
   from dual 
   connect by level <= (
     months_between ( trunc ( date'2024-03-01', 'y' ), trunc ( date'2010-01-31', 'y' ) )
   ) / 12 
), dates as ( 
   select trunc ( date'2010-01-31', 'iyyy' ) + ( level / 500 ) dt
   from dual 
   connect by level <= (
     trunc ( date'2024-03-01', 'iw' ) - trunc ( date'2010-01-31', 'iyyy' )
   ) * 500 
) 
select * from (
select dt, dt + 7, competition_id, 'FINAL' from dates_w
cross join competitions
where  competition_type_id = 1
union all
-- daily
select dt, dt + 1, competition_id, 'FINAL' from dates_d
cross join competitions
where  competition_type_id = 3
union all
-- champs
select dt + 7, dt + 7 + 1/24, competition_id, 'RANKED' from dates_y
cross join competitions
where  competition_type_id = 2
union all
-- one-off
select dt, dt + 1, competition_id, 'FINAL' from dates
cross join competitions
where  competition_type_id = 4
)
order  by 1;

commit;

insert into quiz_results
select quiz_id, 
       user_id, 
       start_date,
       case mod ( quiz_id + user_id, 50 ) 
         when 0 then null 
         else start_date + ( time_taken / 86400 )
       end, 
       pct_correct,   
       time_taken
from ( 
select quiz_id, 
       user_id, 
       start_date + dbms_random.value ( 0, (end_date - start_date ) * 86400 ) / 86400 start_date,
       dbms_random.value ( 0, 100 ) pct_correct,   
       dbms_random.value ( 30, 600 ) time_taken
from (
    select /*+ no_merge */quiz_id, 
    start_date, end_date,
    case 
      when competition_id between 1 and 5 then dbms_random.value ( 50, 500 ) 
      when competition_id between 6 and 10 then 30
      when competition_id between 11 and 15 then dbms_random.value ( 1, 10 ) 
      when competition_id > 15 then 1
    end num_players,
    competition_id
    from quizzes 
    where  start_date < date'2015-01-01'
    and    competition_id <= 15
)
cross apply (
    select user_id from users
    order  by dbms_random.value
    fetch first num_players rows only
)
)
order by quiz_id, start_date;

commit;

insert into quiz_results
select quiz_id, 
       user_id, 
       start_date,
       case mod ( quiz_id + user_id, 50 ) 
         when 0 then null 
         else start_date + ( time_taken / 86400 )
       end, 
       pct_correct,   
       time_taken
from ( 
select quiz_id, 
       user_id, 
       start_date + dbms_random.value ( 0, (end_date - start_date ) * 86400 ) / 86400 start_date,
       dbms_random.value ( 0, 100 ) pct_correct,   
       dbms_random.value ( 30, 600 ) time_taken
from (
    select /*+ no_merge */quiz_id, 
    start_date, end_date,
    case 
      when competition_id between 1 and 5 then dbms_random.value ( 50, 500 ) 
      when competition_id between 6 and 10 then 30
      when competition_id between 11 and 15 then dbms_random.value ( 1, 10 ) 
      when competition_id > 15 then 1
    end num_players,
    competition_id
    from quizzes 
   where  start_date >= date'2015-01-01'
   and    start_date < date'2020-01-01'
   and    competition_id <= 15
)
cross apply (
    select user_id from users
    order  by dbms_random.value
    fetch first num_players rows only
)
)
order by quiz_id, start_date;

commit;

insert into quiz_results
select quiz_id, 
       user_id, 
       start_date,
       case mod ( quiz_id + user_id, 50 ) 
         when 0 then null 
         else start_date + ( time_taken / 86400 )
       end, 
       pct_correct,   
       time_taken
from ( 
select quiz_id, 
       user_id, 
       start_date + dbms_random.value ( 0, (end_date - start_date ) * 86400 ) / 86400 start_date,
       dbms_random.value ( 0, 100 ) pct_correct,   
       dbms_random.value ( 30, 600 ) time_taken
from (
    select /*+ no_merge */quiz_id, 
    start_date, end_date,
    case 
      when competition_id between 1 and 5 then dbms_random.value ( 50, 500 ) 
      when competition_id between 6 and 10 then 30
      when competition_id between 11 and 15 then dbms_random.value ( 1, 10 ) 
      when competition_id > 15 then 1
    end num_players,
    competition_id
    from quizzes 
    where  start_date >= date'2020-01-01'
    and    competition_id <= 15
)
cross apply (
    select user_id from users
    order  by dbms_random.value
    fetch first num_players rows only
)
)
order by quiz_id, start_date;

commit;

insert into quiz_results
select quiz_id, 
       user_id, 
       start_date, 
       case mod ( quiz_id + user_id, 50 ) 
         when 0 then null 
         else start_date + ( time_taken / 86400 )
       end, 
       pct_correct, 
       time_taken 
from (
    select /*+ no_merge */quiz_id, 
    start_date + dbms_random.value ( 0, (end_date - start_date ) * 86400 ) / 86400 start_date,
    dbms_random.value ( 0, 100 ) pct_correct,   
    dbms_random.value ( 30, 600 ) time_taken,
    round ( dbms_random.value ( 1, 100000 ) ) user_id
    from quizzes 
    where  competition_id > 15--start_date >= date'2020-01-01'
)
order by quiz_id, start_date;

commit;

select competition_id, count(*) from quizzes
where  status = 'RANKED'
group  by competition_id;

select status, count(*) from quizzes
where  competition_id = 1
group  by status;

create index quiz_competition_i on quizzes ( competition_id );
create index comp_type_i on competitions ( competition_type_id );
create index qure_user_i on quiz_results ( user_id );
create index qure_result_date_i on quiz_results ( result_date );
create index ques_create_date_i on questions ( created_date ) invisible;
create index quiz_status_i on quizzes ( status ) invisible;
create index quiz_start_i on quizzes ( start_date ) invisible;

create materialized view mv_results
as 
select row_number() over ( 
         partition by quiz_id 
         order by pct_correct desc, seconds_taken desc 
       ) rank, 
       quiz_id, 
       user_id,
       username,
       pct_correct,
       seconds_taken 
from   quiz_results 
join   users 
using ( user_id );

create index mvre_quiz_i on mv_results ( quiz_id ) invisible;

create materialized view year_stats 
as 
select trunc ( result_date, 'y' ) year_start, 
       count(*) num_answers, 
       count ( distinct user_id ) num_users, 
       sum ( case when ( finish_date - result_date ) < 1/24 then seconds_taken end ) total_time
from   quiz_results 
where  finish_date is not null;

create materialized view year_stats_rollup
as 
select trunc ( result_date, 'y' ) year_start, 
       count(*) num_answers, 
       count ( distinct user_id ) num_users, 
       sum ( case when ( finish_date - result_date ) < 1/24 then seconds_taken end ) total_time
from   quiz_results 
where  finish_date is not null
group  by rollup ( trunc ( result_date, 'y' ) );


exec dbms_stats.gather_table_stats ( ownname => null, tabname => 'competitions' );
exec dbms_stats.gather_table_stats ( ownname => null, tabname => 'quizzes' );
exec dbms_stats.gather_table_stats ( ownname => null, tabname => 'quiz_results' );
exec dbms_stats.gather_table_stats ( ownname => null, tabname => 'competition_types' );
exec dbms_stats.gather_table_stats ( ownname => null, tabname => 'mv_results' );
exec dbms_stats.gather_table_stats ( ownname => null, tabname => 'year_stats' );
exec dbms_stats.gather_table_stats ( ownname => null, tabname => 'year_stats_rollup' );