cl scr
drop table game_countries
  cascade constraints purge;
drop table games
  cascade constraints purge;
drop table countries
  cascade constraints purge;
drop table game_statuses
  cascade constraints purge;

create table countries (
/*  country_id integer
    generated by default as identity
    not null 
    primary key,/**/
  country_iso_code varchar2(2)
    not null
     primary key, 
--     unique,
  country_name varchar2(256)
    not null,
  home_timezone varchar2(256)
    not null
);

begin
  insert into countries ( country_iso_code, country_name, home_timezone ) 
     values ( 'GB', 'United Kingdom', 'Europe/London' );
  insert into countries ( country_iso_code, country_name, home_timezone ) 
    values ( 'US', 'USA', 'America/Los_Angeles' );
  insert into countries ( country_iso_code, country_name, home_timezone ) 
     values ( 'DE', 'Germany', 'Europe/Berlin' );
  insert into countries ( country_iso_code, country_name, home_timezone ) 
     values ( 'IN', 'India', 'Asia/Kolkata' );
end;
/
commit;


create table game_statuses (
  game_status_id varchar2(10)
    not null
    primary key,
  description varchar2(100)
    not null
);

insert into game_statuses values ( 'SCHEDULED', 'The game is planned' );
insert into game_statuses values ( 'COMPLETED', 'The game has finished' );
insert into game_statuses values ( 'CANCELLED', 'The game was called off' );
commit;
/**/

create table games (
  game_id integer
    generated by default as identity
    not null
    primary key
, game_time timestamp 
    with time zone -- uncomment if with TZ
    not null
, game_status varchar2(10)
    references game_statuses
/*    constraint game_status_c check ( 
      game_status in ( 'SCHEDULED', 'COMPLETED', 'CANCELLED' ) 
    ) /**/
    not null
  /* Comment back in for columns */
, home_country
    references countries
, away_country
    references countries
, home_score integer
--    default on null 0
--    not null
, away_score integer
--    default on null 0
--    not null
/* Comment in for storing points with columns /**/
/*, home_points integer
    default on null 0
    not null
, away_points integer
    default on null 0
    not null
, check ( home_country <> away_country )
/**/
);

/* Create if rows */

/*
create table game_countries (
  game_id 
    references games
    not null
, country_id
    references countries
    not null
, home_away varchar2(4)
    check ( home_away in ( 'HOME', 'AWAY' ) )
    not null
, score     integer
    default on null 0
    not null
,  points    integer
    default on null 0
    not null
, unique ( game_id, country_id )
, unique ( game_id, home_away )
);
/**/

create or replace function get_country_id ( iso_code varchar2 ) 
  return varchar2 as
  country_id varchar2(2);
begin
  select country_id into country_id 
  from   countries
  where  country_iso_code = iso_code;
  return nvl ( country_id, iso_code );
end;
/
  
   
declare
  use_columns  boolean := true;
  store_points boolean := false;
  use_utc      boolean := false;
  procedure ins_game ( 
    game_status  varchar2, game_time games.game_time%type,
    home_country varchar2, away_country varchar2, 
    home_score   int,      away_score int, 
    home_points  int,      away_points int
  ) as
    stmt clob;
  begin
    stmt := 'insert into games ( game_status, game_time ' ||
    case when use_columns then 
    ', home_country, away_country, home_score, away_score '
    end ||
    case when use_columns and store_points then 
    ', home_points, away_points '
    end ||
    ') values ( :game_status, :game_time ' ||
    case when use_utc then
    q'[ at time zone 'UTC' ]'
    end || 
    case when use_columns then 
    ', get_country_id ( :home_country ), get_country_id ( :away_country ) 
    , :home_score, :away_score '
    end ||
    case when use_columns and store_points then 
    ', :home_points, :away_points '
    end || 
    ')';
    
    dbms_output.put_line ( stmt );
    dbms_output.put_line ( game_time );
    
    if use_columns and store_points then
      execute immediate stmt
      using game_status, game_time
        , home_country, away_country, home_score, away_score 
        , home_points, away_points;
    elsif use_columns then 
      execute immediate stmt
      using game_status, game_time
        , home_country, away_country, home_score, away_score;
    else
      execute immediate stmt
      using game_status, game_time;
    end if;
  end ins_game;

begin
  ins_game ( 
    'COMPLETED', timestamp'2022-11-05 15:00:00 Europe/London' 
  , 'GB', 'US', 3, 1
  , 3, 0 
  );
  ins_game ( 
    'COMPLETED', timestamp'2022-11-05 15:00:00 Europe/Berlin' 
  , 'DE', 'IN', 2, 2, 1, 1
  );
  ins_game ( 
    'COMPLETED', timestamp'2022-11-12 15:00:00 Asia/Kolkata' 
  , 'IN', 'GB', 0, 0, 1, 1
  );
  ins_game ( 
    'COMPLETED', timestamp'2022-11-12 15:00:00 America/Los_Angeles' 
  , 'US', 'DE', 1, 4, 0, 3
  );
  ins_game ( 
    'SCHEDULED', timestamp'2022-11-19 15:00:00 America/Los_Angeles' 
  , 'US', 'IN', null, null, null, null
  );
  ins_game ( 
    'SCHEDULED', timestamp'2022-11-19 15:00:00 Europe/Berlin' 
  , 'DE', 'GB', null, null, null, null
  );
  ins_game ( 
    'SCHEDULED', timestamp'2022-11-26 15:00:00 America/Los_Angeles' 
  , 'US', 'GB', null, null, null, null
  );
  ins_game ( 
    'SCHEDULED', timestamp'2022-11-26 15:00:00 Asia/Kolkata' 
  , 'IN', 'DE', null, null, null, null
  );
end;
/

-- Uncomment for rows
/*
begin
  insert into game_countries ( game_id, country_id, home_away, score ) 
    values ( 1, get_country_id ( 'GB' ), 'HOME', 3 );
  insert into game_countries ( game_id, country_id, home_away, score ) 
    values ( 1, get_country_id ( 'US' ), 'AWAY', 1 );
  
  insert into game_countries ( game_id, country_id, home_away, score ) 
    values ( 2, get_country_id ( 'DE' ), 'HOME', 2 );
  insert into game_countries ( game_id, country_id, home_away, score ) 
    values ( 2, get_country_id ( 'IN' ), 'AWAY', 2 );
  
  insert into game_countries ( game_id, country_id, home_away, score ) 
    values ( 3, get_country_id ( 'IN' ), 'HOME', 0 );
  insert into game_countries ( game_id, country_id, home_away, score) 
    values ( 3, get_country_id ( 'GB' ), 'AWAY', 0 );
  
  insert into game_countries ( game_id, country_id, home_away, score
  ) values ( 4, get_country_id ( 'US' ), 'HOME', 1 );
  insert into game_countries ( game_id, country_id, home_away, score ) 
    values ( 4, get_country_id ( 'DE' ), 'AWAY', 4 );
  
  insert into game_countries ( game_id, country_id, home_away )
    values ( 5, get_country_id ( 'US' ), 'HOME' );
  insert into game_countries ( game_id, country_id, home_away )
    values ( 5, get_country_id ( 'IN' ), 'AWAY' );
  
  insert into game_countries ( game_id, country_id, home_away )
    values ( 6, get_country_id ( 'DE' ), 'HOME' );
  insert into game_countries ( game_id, country_id, home_away )
    values ( 6, get_country_id ( 'GB' ), 'AWAY' );
  
  insert into game_countries ( game_id, country_id, home_away )
    values ( 7, get_country_id ( 'US' ), 'HOME' );
  insert into game_countries ( game_id, country_id, home_away )
    values ( 7, get_country_id ( 'GB' ), 'AWAY' );
  
  insert into game_countries ( game_id, country_id, home_away )
    values ( 8, get_country_id ( 'IN' ), 'HOME' );
  insert into game_countries ( game_id, country_id, home_away )
    values ( 8, get_country_id ( 'DE' ), 'AWAY' );
end;
/
/**/
  
/* Store points if necessary */
/* Uncomment for countries as rows */
/*
update game_countries g
set    points = ( 
  select case
      when home_score = away_score then 1
      when home_away = 'HOME' and home_score > away_score then 3
      when home_away = 'AWAY' and home_score < away_score then 3
      else 0
    end p
  from (
    select *
    from   game_countries c
    where  g.game_id = c.game_id
  )
  pivot (
    max ( country_id ) country, max ( score ) score
    for home_away in ( 'HOME' home, 'AWAY' away )
  )
)
where  game_id in ( 1, 2, 3, 4 );
/**/

/* Uncomment for countries as columns */
/*
update games
set    ( home_points, away_points ) = ( 
  select case
      when home_score > away_score then 3
      when home_score = away_score then 1
      when home_score < away_score then 0
    end, case
      when home_score > away_score then 0
      when home_score = away_score then 1
      when home_score < away_score then 3
    end
  from dual 
)
where  game_id in ( 1, 2, 3, 4 );
/**/

commit;


/* Check our tables */
alter session set nls_timestamp_format = ' DD Mon HH24:MI ';
alter session set nls_timestamp_tz_format = ' DD Mon HH24:MI TZR';

select * from countries;
select * from games;
select * from game_countries;






/********************

 Get all the games for a team
 With start times in their country's TZ 
 Show the result W/D/L for completed games

********************/

-- Rows

select * from (
  select 
         max ( -- get the local time for the country of interest
           case when :country = country_iso_code then
--             game_time at time zone home_timezone 
             from_tz ( game_time, 'UTC' ) at time zone home_timezone 
           end 
         ) over ( partition by game_id ) game_time, 
         home_away, country_iso_code, score, game_status, game_id
  from   games
  join   game_countries
  using  ( game_id )
  join   countries
--  on     country_id = country_iso_code
  using  ( country_id )
)
pivot (
  max ( country_iso_code ) country, max ( score ) score
  for home_away in ( 'HOME' home, 'AWAY' away )
) m
where  :country in ( home_country, away_country ) ;

-- Columns 

select 
--         from_tz ( game_time, 'UTC' ) at time zone home_timezone game_time, 
       game_time at time zone home_timezone game_time, 
       game_status, home_score, away_score, home_country, away_country
from   games
join   countries
/* Surrogates */
--on     country_id in ( home_country, away_country )
--where  get_country_id ( :country ) = country_id;
/* Natural */
on     country_iso_code in ( home_country, away_country )
where  get_country_id ( :country ) = country_iso_code;




create or replace function country_games ( 
  country varchar2
) return clob sql_macro as
begin
  return q'!
select 
--         from_tz ( game_time, 'UTC' ) at time zone home_timezone game_time, 
       game_time at time zone home_timezone game_time, 
       game_status, home_score, away_score, home_country, away_country
from   games
join   countries
/* Surrogates */
--on     country_id in ( home_country, away_country )
--where  get_country_id ( :country ) = country_id;
/* Natural */
on     country_iso_code in ( home_country, away_country )
where  get_country_id ( country ) = country_iso_code
!';
end country_games;
/

select * from country_games ( :country );

/* Add in result */
select 
       game_time
     , home_country, away_country
     , home_score, away_score
     , case 
         when game_status <> 'COMPLETED' then 'TBC'
         when home_score = away_score then 'D'
         when home_score > away_score and home_country = :country then 'W'
         when home_score < away_score and away_country = :country then 'W'
         else 'L'
       end result
from   country_games ( :country )
order  by game_time;




/********************

 Get the upcoming games
 In the session TZ

********************/

-- Using rows 

with rws as (  
  select game_time, country_id as country_iso_code, home_away 
  from   games
  join   game_countries
  using  ( game_id )
)
  select 
     from_tz ( game_time, 'UTC' ) at local game_time, 
--     game_time at local game_time, 
     home_country, away_country  
  from   rws
  pivot (
    max ( country_iso_code ) country
    for home_away in ( 'HOME' home, 'AWAY' away )
  );

-- Using columns 
select 
--         from_tz ( game_time, 'UTC' ) at local game_time, 
       game_time at local game_time, 
       home.country_iso_code location,
       home_country, away_country
from   games
join   countries home
--on     home_country = home.country_id
on     home_country = home.country_iso_code
/


create or replace function fixtures 
  return clob sql_macro as
begin
  return q'! 
select 
--         from_tz ( game_time, 'UTC' ) at local game_time, 
       game_time at local game_time, 
       home.country_iso_code location,
       home_country, away_country
from   games
join   countries home
--on     home_country = home.country_id
on     home_country = home.country_iso_code
!';
end fixtures;
/


select game_time
/* Uncomment for surrogate/natural as needed */
, home_country, away_country
--, home.country_iso_code home_country, away.country_iso_code away_country
from   table ( fixtures )
/* Comment in if using surrogate keys */
/*join   countries home
on     home_country = home.country_id
join   countries away
on     away_country = away.country_id /**/
where  game_time >= timestamp'2022-11-16 00:00:00 UTC'
and    game_time < timestamp'2022-11-23 00:00:00 UTC'
order  by game_time;

/* Re-run for different time zones */
alter session set time_zone = 'Europe/Berlin';
alter session set time_zone = 'Asia/Kolkata';
alter session set time_zone = 'Europe/London';


/********************

 Generate the league
 Won/Drawn/Lost counts
 Score difference
 Points (Win = 3, Draw = 1, Loss = 0)

 Start with points/score diff/WDL for each team

********************/

-- Rows

with rws as (  
  select team.country_id country
    , ( team.score - oppo.score ) as score_diff
    , case 
        when team.score > oppo.score then 'W' 
        when team.score = oppo.score then 'D' 
        when team.score < oppo.score then 'L'
      end wdl
    , team.points
--    , case 
--        when team.score > oppo.score then 3 
--        when team.score = oppo.score then 1 
--        when team.score < oppo.score then 0 
--      end points
  from   games g
  join   game_countries team
  on     g.game_id = team.game_id
  join   game_countries oppo
  on     g.game_id = oppo.game_id
  and    oppo.country_id <> team.country_id
  where  game_status = 'COMPLETED'
)
  select country
       , sum ( points ) points, count ( wdl ) games, sum ( score_diff ) score_diff
--       , points, wdl, score_diff
  from   rws
  group  by country;

-- Columns

with rws as (
  select home_country, away_country
    , ( home_score - away_score ) as home_diff
    , ( away_score - home_score ) as away_diff
    , case 
        when home_score > away_score then 'W' 
        when home_score = away_score then 'D' 
        when home_score < away_score then 'L'
      end home_wdl
    , case 
        when home_score > away_score then 'L' 
        when home_score = away_score then 'D' 
        when home_score < away_score then 'W'
      end away_wdl
    /* Change commenting for calc/store points */
--    , home_points, away_points
    , case 
        when home_score > away_score then 3 
        when home_score = away_score then 1 
        when home_score < away_score then 0 
      end home_points
    , case 
        when home_score > away_score then 0
        when home_score = away_score then 1 
        when home_score < away_score then 3 
      end away_points /**/
  from   games
  where  game_status = 'COMPLETED'
)
select country
     , sum ( points ), count ( wdl ) games, sum ( score_diff ) score_diff
--     , points, wdl, score_diff
from   rws
unpivot (
  ( country, points, wdl, score_diff ) for home_away in ( 
    ( home_country, home_points, home_wdl, home_diff ) as 'HOME',
    ( away_country, away_points, away_wdl, away_diff ) as 'AWAY'
  )
)
group  by country;


/********************/


/* !! REMOVE GROUP BY & SUMs when pasting !! */ 
create or replace function country_results 
  return clob sql_macro as
begin
  return q'! 
with rws as (
  select home_country, away_country
    , ( home_score - away_score ) as home_diff
    , ( away_score - home_score ) as away_diff
    , case 
        when home_score > away_score then 'W' 
        when home_score = away_score then 'D' 
        when home_score < away_score then 'L'
      end home_wdl
    , case 
        when home_score > away_score then 'L' 
        when home_score = away_score then 'D' 
        when home_score < away_score then 'W'
      end away_wdl
    /* Change commenting for calc/store points */
--    , home_points, away_points
    , case 
        when home_score > away_score then 3 
        when home_score = away_score then 1 
        when home_score < away_score then 0 
      end home_points
    , case 
        when home_score > away_score then 0
        when home_score = away_score then 1 
        when home_score < away_score then 3 
      end away_points /**/
  from   games
  where  game_status = 'COMPLETED'
)
select country
     , points, wdl, score_diff
from   rws
unpivot (
  ( country, points, wdl, score_diff ) for home_away in ( 
    ( home_country, home_points, home_wdl, home_diff ) as 'HOME',
    ( away_country, away_points, away_wdl, away_diff ) as 'AWAY'
  )
)
  !';
end country_results;
/

/* Wins/draws/losses per team */
select * from table ( country_results );






/* One row/team */
select * from table ( country_results )
pivot (
  count(*) c
, sum ( score_diff ) diff
, sum ( points ) points 
  for wdl in ( 'W' W, 'D' D, 'L' L )
);

create or replace function league 
  return clob sql_macro as
begin
  return q'! 
select * from table ( country_results )
pivot (
  count(*) c
, sum ( score_diff ) diff
, sum ( points ) points 
  for wdl in ( 'W' W, 'D' D, 'L' L )
)  
!';
end league;
/

/* The final league */
select country_name, w_c w, d_c d, l_c l, 
       nvl ( w_points, 0 ) + nvl ( d_points, 0 ) points,
       nvl ( w_diff, 0 ) + nvl ( d_diff, 0 ) + nvl ( l_diff, 0 ) score_diff
from   table ( league )
join   countries 
--on     country = country_id
on     country = country_iso_code
order  by points desc, score_diff desc;






/* !! US-IN game abandonded !! */
update games
set    game_status = 'ABANDONED'
where  game_id = 4;

/* Need to add new status - DML or DDL? */
--insert into game_statuses 
--  values ( 'ABANDONED', 'The game was stopped' );

/*
alter table games
  add constraint game_statuses_c
  check ( 
    game_status in ( 'SCHEDULED', 'COMPLETED', 'CANCELLED', 'ABANDONED' ) 
  );
alter table games
  drop constraint game_status_c;
/**/
  
update games
set    game_status = 'ABANDONED'
where  game_id = 4;






/* So what's the benefit of check constraints?! */
--alter table games
--  add constraint game_statuses_c
--  check ( 
--    game_status in ( 'SCHEDULED', 'COMPLETED', 'CANCELLED', 'ABANDONED' ) 
--  );

/* Optimizer knows which values are impossible! */
select * from games
where  game_status = 'JUNK';